# Generated by Django 3.1.1 on 2020-09-10 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfoCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_of_registration', models.DateTimeField(verbose_name='date registered')),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DetailInfoCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
                ('basic_info_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_cards.basicinfocard')),
            ],
        ),
        migrations.AddField(
            model_name='basicinfocard',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='info_cards.breed'),
        ),
        migrations.AddField(
            model_name='basicinfocard',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='info_cards.sex'),
        ),
        migrations.AddField(
            model_name='basicinfocard',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='info_cards.size'),
        ),
        migrations.AddField(
            model_name='basicinfocard',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='info_cards.species'),
        ),
    ]
