# Generated by Django 3.1.1 on 2020-09-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sex',
            name='sex',
            field=models.CharField(max_length=20),
        ),
    ]
